# Generated by Django 6.0.3 on 2026-03-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedHyperparams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('hidden_size', models.IntegerField()),
                ('num_layers', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('epochs', models.IntegerField()),
                ('val_mse', models.FloatField()),
                ('directional_accuracy', models.FloatField()),
                ('composite_fitness', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
