# Generated by Django 4.2.29 on 2026-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizedHyperparams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('hidden_size', models.IntegerField()),
                ('num_layers', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('epochs', models.IntegerField()),
                ('dropout', models.FloatField()),
                ('seq_len', models.IntegerField()),
                ('val_mse', models.FloatField()),
                ('directional_accuracy', models.FloatField()),
                ('composite_fitness', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchedTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
