# Generated by Django 5.0.14 on 2026-03-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-search_count'],
            },
        ),
        migrations.AlterField(
            model_name='optimizedhyperparams',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
