# Generated by Django 5.0.14 on 2026-03-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_searchedticker_alter_optimizedhyperparams_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizedhyperparams',
            name='dropout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='optimizedhyperparams',
            name='seq_len',
            field=models.IntegerField(default=20),
        ),
    ]
