# Generated by Django 5.0.14 on 2026-04-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_optimizedhyperparams_dropout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizedhyperparams',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchedticker',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
