[theme]
base                     = "dark"
primaryColor             = "#2196F3"
backgroundColor          = "#131722"
secondaryBackgroundColor = "#1E222D"
textColor                = "#D1D4DC"
font                     = "sans serif"
